// <auto-generated />
using System;
using HeadhuntersCandidatesDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeadhuntersCandidatesDatabase.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221120232214_HCDb")]
    partial class HCDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.CandidateSkillset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int?>("SkillListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillListId");

                    b.ToTable("CandidateSkillset");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.CompanyPositions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("PositionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PositionsId");

                    b.ToTable("CompanyPositions");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.PositionSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int?>("SkillListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("SkillListId");

                    b.ToTable("PositionSkills");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.CandidateSkillset", b =>
                {
                    b.HasOne("HeadhuntersCandidatesDatabase.Core.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeadhuntersCandidatesDatabase.Core.Models.Skill", "SkillList")
                        .WithMany()
                        .HasForeignKey("SkillListId");

                    b.Navigation("Candidate");

                    b.Navigation("SkillList");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.CompanyPositions", b =>
                {
                    b.HasOne("HeadhuntersCandidatesDatabase.Core.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeadhuntersCandidatesDatabase.Core.Models.Position", "Positions")
                        .WithMany()
                        .HasForeignKey("PositionsId");

                    b.Navigation("Company");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("HeadhuntersCandidatesDatabase.Core.Models.PositionSkills", b =>
                {
                    b.HasOne("HeadhuntersCandidatesDatabase.Core.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeadhuntersCandidatesDatabase.Core.Models.Skill", "SkillList")
                        .WithMany()
                        .HasForeignKey("SkillListId");

                    b.Navigation("Position");

                    b.Navigation("SkillList");
                });
#pragma warning restore 612, 618
        }
    }
}
